# Generated by Django 5.2 on 2025-05-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
